language: node_js
node_js:
  - "node"
  - "lts/*"
cache: npm
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
