version: "3"

services:
  avatar_nodejs:
    build: .
    image: frncsdrk/avatar:latest
    container_name: avatar_nodejs
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - avatar

networks:
  avatar:
    driver: bridge
