version: "3"

services:
  avatar_nodejs:
    build: .
    image: avatar_nodejs:dev
    container_name: avatar_nodejs_dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - avatar

networks:
  avatar:
    driver: bridge
