name: push-tag

on:
  create:
    tags:
      - 1.*
      # NOTE: Update on major version change

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: frncsdrk/avatar
          registry: docker.io
          tags: ${{ env.RELEASE_VERSION }}, stable
          dockerfile: ./Dockerfile
          directory: ./
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
