name: push-latest

on:
  push:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: frncsdrk/avatar
      #     registry: docker.io
      #     tags: latest
      #     dockerfile: ./Dockerfile
      #     directory: ./
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: frncsdrk/avatar:latest
