name: push-latest

on:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: frncsdrk/avatar
          registry: docker.io
          tags: latest
          dockerfile: ./Dockerfile
          directory: ./
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
